spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

config-params:
  min-score: ${MIN_SCORE}
  max-score: ${MAX_SCORE}
  top-score-players-limit: ${TOP_SCORE_PLAYERS_LIMIT}

server:
  error:
    include-stacktrace: never
    include-exception: false
