spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webGejemikaDB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

config-params:
  min-score: 8
  max-score: 21
  top-score-players-limit: 10

server:
  error:
    include-stacktrace: never
    include-exception: false
