spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webGejmikaDB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

config-params:
  games:
    gejmika:
      minScore: 8
      maxScore: 21
      topScorePlayersLimit: 10
    bombika:
      minScore: 1
      maxScore: 100
      topScorePlayersLimit: 10


server:
  error:
    include-stacktrace: never
    include-exception: false